src/library/getOptions.js

save testing for Kim. Another review post merge pls.

fix: 958 resolve duplicate mr error when trying to map undefined things

---

src/App/App.js
src/App/useInitializeBellNotifications.js
src/App/useInitializeCurrentUser.js

This fixes broken develop
Steps to test: does the app run or crash?

Fix: M842] using useHandleREsponseErrorHandler that depended on context outside of context

---

package.json
src/components/BellNotificationDropDown/BellNotificationDropDown.js
yarn.lock

Testing requires editing code/mocking api responses. Leave for @saanobhaai

fix: 775 Accept html in notification description

---

src/components/pages/Collect/AddSampleUnitButton.js
src/components/pages/Submitted/SubmittedToolbarSection.js

[trello ticket 965](https://trello.com/c/M95XaBEV/965-rearrange-the-method-list-in-the-collecting-page-and-submitted-page)
to test:
ensure order items are as follows in the ‘+ Add Sample Unit’ under the Collecting Page and ‘Export To XLSX’ under the Submitted Page
Fish belt
Benthic PIT
Benthic LIT
Benthic Photo Quadrat
Bleaching
Habitat Complexity

rearrange menu items for export csv and add sample unit

---

src/App/mermaidData/databaseSwitchboard/ManagementRegimesMixin.js
src/App/mermaidData/databaseSwitchboard/SitesMixin.js
src/App/mermaidData/databaseSwitchboard/SubmittedRecordsMixin.js
src/components/CopyManagementRegimesModal/CopyManagementRegimesModal.js
src/components/CopySitesModal/CopySitesModal.js
src/library/constants/constants.js

Add pagination to api calls for tables:
- Copy MRs table
- Copy Sites table
- Submitted table

Nick/M959 Improve api load without setting fixed limit

---

src/components/ProjectCard/ProjectCard.styles.js
src/components/generic/form.js
src/components/pages/Submitted/SubmittedToolbarSection.js

Multiple tickets. See commit messages.

Minor UI tweaks

---

src/components/mermaidInputs/InputRadioWithLabelAndValidation/InputRadioWithLabelAndValidation.js
src/components/mermaidInputs/InputValidationInfo/InputValidationInfo.js
src/components/pages/collectRecordFormPages/CollectRecordFormPage/CollectRecordFormPage.js
src/components/pages/collectRecordFormPages/CollectingFormPage.Styles.js
src/components/pages/collectRecordFormPages/FishBeltForm/FishBeltObservationTable.js
src/components/pages/collectRecordFormPages/FishBeltForm/FishBeltTransectInputs.js
src/language.js

Fish bin size and observation table should be linked. 
- Shouldn’t be able to change the fish bin size if there’s observations.
- Shouldn’t be able to add any observations if fish bin size isn’t selected.

Nick/M804 - Link fish size bin and fish observations

---

src/App/App.js
src/App/mermaidData/databaseSwitchboard/tests/testHelpers.DatabseSwitchboard.js
src/App/mermaidData/pullApiData.js
src/App/mermaidData/syncApiDataIntoOfflineStorage/SyncApiDataInfoOfflineStorage.test.js
src/App/mermaidData/syncApiDataIntoOfflineStorage/SyncApiDataIntoOfflineStorage.js
src/components/pages/Projects/Projects.test.js
src/testUtilities/mockOnlineDatabaseSwitchboardInstance.js

Whats going on in this PR? Well, we are rethinking the pull sync errors stuff, so I didnt push my work for that, but part of that work involved:
- addressing some previous PR stuff as promised 
- updating some var names to be better
No testing required. This is just refactoring.

chore: code improvements from abandoned ticket # 970

---

src/App/App.js
src/App/bellNotificationHelpers.js
src/App/useInitializeBellNotifications.js
src/components/BellNotificationDropDown/BellNotificationDropDown.js
src/components/BellNotificationDropDown/BellNotificationDropDown.styles.js
src/language.js

[dismiss-all trello card](https://trello.com/c/xL50hzay/380-dismiss-all-link-at-top-of-bell-notifications)
Add functionality to the existing button in the attached branch to clear all notifications in the bell noti dropdown
to test:
- Clicking the button does not close the notification list pop over.
- Clicking the button will clear all the notifications and display the "There are currently no notifications" text.
- Only show the dismiss all notification button if there are one or more notifications.

[Feature] Add dismiss all notification button

---

src/components/pages/submittedRecordPages/SubmittedBleaching/SubmittedBleaching.js

[trello card ](https://trello.com/c/g5AoFp7C/530-cant-move-submitted-bleaching-su-to-collecting)
to test:
1. go to submitted
2. click on a submitted bleaching record
3. move to collecting
4. ensure you get a confirmation that record has been moved, and a 404

Bug fix [530] can't move submitted bleaching SU to Collecting

---

src/components/generic/Table/PageSizeSelector/PageSizeSelector.js
src/components/pages/Collect/Collect.js
src/components/pages/ManagementRegimes/ManagementRegimes.js
src/components/pages/Sites/Sites.js
src/components/pages/Submitted/Submitted.js
src/components/pages/Users/Users.js
src/components/pages/UsersAndTransects/UsersAndTransects.js

[trello card](https://trello.com/c/qaa9RPuv/529-text-updates-for-pagination-filtering)

[529] Pagination text updates

---

src/components/FilterSearchToolbar/FilterSearchToolbar.js
src/components/MethodsFilterDropDown/MethodsFilterDropDown.js
src/components/generic/positioning.js
src/components/pages/Collect/Collect.js
src/components/pages/ManagementRegimesOverview/ManagementRegimesOverview.js
src/components/pages/Submitted/SubmittedToolbarSection.js
src/components/pages/UsersAndTransects/UsersAndTransects.js

[trello card](https://trello.com/c/bj8LiCKZ/512-update-styles-for-method-filter-to-match-rest-of-site)
changes include:
Method filter positioning (next to search bar)
Hover styles
focus outline
Font
Font size
Font colour
Input label
to test:
1. go to either collect, MRO, users
2. go to method filter
3. ensure style changes match UI image in trello card

Method filter style updates

---

src/components/generic/FilterIndicatorPill/FilterIndicatorPill.js
src/components/generic/Table/PageSizeSelector/PageSizeSelector.js
src/components/pages/Collect/Collect.js
src/components/pages/ManagementRegimesOverview/ManagementRegimesOverview.js
src/components/pages/Submitted/Submitted.js
src/components/pages/Submitted/SubmittedToolbarSection.js
src/components/pages/UsersAndTransects/UsersAndTransects.js

[trello card](https://trello.com/c/w1lBYnlE/535-add-a-label-pill-to-indicate-the-number-of-filtered-rows-in-a-table)
summary: 
Add a label or pill next to the filter method selector when the text filter and/or the method filter is applied.
to test:
1. go to collect, submitted, users, MRO
2. apply text filter and method filter
3. see label pill appear
4. press 'x' to clear filters

[535] Label pill for filters

---

src/components/pages/Collect/Collect.js
src/components/pages/ManagementRegimesOverview/ManagementRegimesOverview.js
src/components/pages/Submitted/Submitted.js
src/components/pages/Submitted/SubmittedToolbarSection.js
src/components/pages/UsersAndTransects/UsersAndTransects.js

[trello ticket](https://trello.com/c/Uw3Kgwfd/541-filter-does-not-clear-when-x-on-the-pill-is-clicked-actually-toggles-the-value)

[541] bug fix for clearing filters

---

src/components/generic/Table/table.js

[trello card](https://trello.com/c/uTlkEKcF/536-popover-stopped-working-on-observers-transects-table)

[536] fix pop-over hover bug

---

src/components/pages/Site/Site.js

add tab key for allowed key presses in long/lat

[542] bug fix for long/lat tab bug in site page

---

src/components/pages/collectRecordFormPages/RecordLevelValidationInfo/RecordLevelValidationInfo.js
src/library/validationMessageHelpers.js

[trello card](https://trello.com/c/EDViYHp5/358-suppress-redundant-system-validation-errors)

[358] suppress redundant 'System Validation' errors

---

src/components/ProjectCard/ProjectCard.js
src/components/ProjectCard/ProjectCard.styles.js

[trello card](https://trello.com/c/mxP0gGXA/365-add-admin-pill-to-project-name)

[365] add admin pill to project

---

src/components/BellNotificationDropDown/BellNotificationDropDown.js

[trello card](https://trello.com/c/qdax2qNb/502-add-support-for-tag-attributes-in-notifications)

[502] add html tag attribute support

---

public/index.html

[trello card](https://trello.com/c/DYBtZzS9/272-add-analytics-to-frontend)

[272] add google analytics tag to index html

---

src/components/mermaidMap/SingleSiteMap/SingleSiteMap.js

[trello card](https://trello.com/c/t1z7Z65H/549-point-does-not-appear-when-creating-a-new-site)

[549] fix pointer on site map

---

src/App/mermaidData/databaseSwitchboard/ProjectsMixin.js
src/components/DeleteProjectButton/DeleteProjectButton.js
src/components/DeleteProjectButton/index.js
src/components/generic/InputAutocomplete/InputAutocomplete.js
src/components/icons.js
src/components/pages/ProjectInfo/ProjectInfo.js
src/components/pages/collectRecordFormPages/CollectingFormPage.Styles.js
src/language.js

[trello card](https://trello.com/c/P4wrqxDo/367-delete-project-main-card)
Add a delete button to delete a project, but only when that project has no data. No mock tests added to this yet.
**note - you will need to pull from dev api before testing this branch**
to test:
**case 1: new project, no sample units or users**
1. create a new project
2. click on project
3. go to project info
4. delete project
**case 2: existing project, with at least one sample unit or user**
1. go to project info
2. delete should be disabled and show warning about removing SU's or users

[367] delete project card

---

src/language.js

[trello card](https://trello.com/c/YF32Gxu5/547-update-the-info-text-for-each-user-on-the-user-page-to-match-the-documentation)

[547] update user page helper text

---

src/App/integrationTests/collectRecords/benthicLit/App.validationIgnoring2BenthicLit.test.js
src/App/integrationTests/collectRecords/benthicPhotoQuadrat/App.validationIgnoring2BenthicPhotoQuadrat.test.js
src/App/integrationTests/collectRecords/benthicPit/App.validationIgnoring2BenthicPit.test.js
src/App/integrationTests/collectRecords/bleaching/App.validationIgnoring2Bleaching.test.js
src/App/integrationTests/collectRecords/fishBelt/App.fishBeltValidationIgnoring2.test.js
src/App/integrationTests/collectRecords/habitatComplexity/App.validationIgnoring2HabitatComplexity.test.js
src/components/mermaidInputs/InputMuiChipSelectWithLabelAndValidation/InputMuiChipSelectWithLabelAndValidation.js
src/components/mermaidInputs/InputMuiChipSelectWithLabelAndValidation/InputMuiChipSelectWithLabelAndValidation.styles.js
src/components/mermaidInputs/InputMuiChipSelectWithLabelAndValidation/index.js
src/components/pages/collectRecordFormPages/ObserversInput/ObserversInput.js

Use MUI chip select component for Observers input in collect record 
https://trello.com/c/kts34j1V/374-prefer-the-drop-down-function-for-observer-name-in-the-v1-version

Melissa/m374 observers to m UI select chip  component

---

src/components/icons.js
src/components/mermaidMap/Map.styles.js
src/components/mermaidMap/SingleSiteMap/SingleSiteMap.js
src/language.js
src/setupTests.js
src/testUtilities/initiallyHydrateOfflineStorageWithMockData.js

[Ticket](https://trello.com/c/kc09LuCI/587-add-place-marker-control-to-map-on-site-page)

M587 add place-marker control to map on site form page

---

src/components/mermaidInputs/InputMuiChipSelectWithLabelAndValidation/InputMuiChipSelectWithLabelAndValidation.js
src/components/mermaidInputs/InputMuiChipSelectWithLabelAndValidation/InputMuiChipSelectWithLabelAndValidation.styles.js

[trello card link](https://trello.com/c/w4faVTCM/599-styles-of-the-new-observers-multi-select-dont-match-the-rest-of-the-application)
updated drop down styles to match the method filter drop down

[599] Update multiselect-chip styles

---

src/components/pages/Sites/Sites.js

Steps to test:
- go to the sites page
- click export sites
- view the CSV file
Sites should be ordered by name
[Ticket](https://trello.com/c/RoVMIBuU/646-sort-by-name-for-exported-sites-and-mrs)

M646 sort sites exported CSV  by site name

---

src/components/RemoveObserverModal/RemoveObserverModal.js
src/components/mermaidInputs/InputMuiChipSelectWithLabelAndValidation/InputMuiChipSelectWithLabelAndValidation.styles.js

[trello card](https://trello.com/c/8Nwg1V2x/634-incorrect-colours-and-button-for-observers-selector)

[634] observers selectors color adjust

---

src/components/RemoveObserverModal/RemoveObserverModal.js
src/components/mermaidInputs/InputMuiChipSelectWithLabelAndValidation/InputMuiChipSelectWithLabelAndValidation.styles.js

Reverts data-mermaid/mermaid-webapp#905

Revert "[634] observers selectors color adjust"

---

src/components/RemoveObserverModal/RemoveObserverModal.js
src/components/mermaidInputs/InputMuiChipSelectWithLabelAndValidation/InputMuiChipSelectWithLabelAndValidation.styles.js

[trello card](https://trello.com/c/8Nwg1V2x/634-incorrect-colours-and-button-for-observers-selector)

[624[ add color adjustments to observers selectors (retry)

---

src/components/generic/Table/TableRowItem/TableRowItem.js
src/components/generic/buttons.js
src/components/generic/form.js
src/components/generic/links.js
src/components/mermaidInputs/InputSelectWithLabelAndValidation/InputSelectWithLabelAndValidation.js
src/components/pages/collectRecordFormPages/SampleEventInputs/SampleEventInputs.js
src/components/pages/submittedRecordPages/SubmittedBenthicLit/SubmittedBenthicLitInfoTable.js
src/components/pages/submittedRecordPages/SubmittedBenthicPhotoQuadrat/SubmittedBenthicPhotoQuadratInfoTable.js
src/components/pages/submittedRecordPages/SubmittedBenthicPit/SubmittedBenthicPitInfoTable.js
src/components/pages/submittedRecordPages/SubmittedBleaching/SubmittedBleachingInfoTable.js
src/components/pages/submittedRecordPages/SubmittedFishBelt/SubmittedFishBeltInfoTable.js
src/components/pages/submittedRecordPages/SubmittedHabitatComplexity/SubmittedHabitatComplexityInfoTable.js
src/language.js

[trello card](https://trello.com/c/DgWFiTJ9/297-link-to-currently-selected-site-mr-in-cr)
to test:
1. go to collect record page
2. select site (view link should activate and link to appropriate site page)
3. select MR, test link
4. go to a submitted record page
5. test site & MR link (underlined link)

[297] add nav links for MR & sites in collect and submitted

---

src/components/pages/collectRecordFormPages/CollectRecordFormPage/useCollectRecordValidation.js
src/language.js

[trello card](https://trello.com/c/S4FefG7b/295-add-toast-or-other-notification-when-validation-completes-without-any-errors-or-unignored-warnings)
add success toast when validation completes without any errors or warnings

[295] add validation success toast

---

src/components/pages/collectRecordFormPages/BenthicLitForm/BenthicLitObservationTable.js
src/components/pages/collectRecordFormPages/BenthicPhotoQuadratForm/BenthicPhotoQuadratObservationTable.js
src/components/pages/collectRecordFormPages/BenthicPitForm/BenthicPitObservationTable.js
src/components/pages/collectRecordFormPages/BleachingForm/ColoniesBleachedObservationsTable.js
src/components/pages/collectRecordFormPages/BleachingForm/PercentCoverObservationsTable.js
src/components/pages/collectRecordFormPages/HabitatComplexityForm/HabitatComplexityObservationTable.js

[trello card](https://trello.com/c/HJzujdWn/655-colour-bar-not-showing-up-in-observation-table-in-bpq)

[655] Observation row error display bug fix on CRs

---

src/components/mermaidMap/SingleSiteMap/SingleSiteMap.js
src/language.js

[trello card](https://trello.com/c/ZBgnL5DE/633-replace-pin-button-states)
to test:
1. go to single site map
2. click place site marker
3. ensure value switches to cancel if no new map placement
4. show 'done' if marker is placed
5. show 'replace pin' if there are existing lng/lat values

[633] update pin button states, update change pin button text

---

src/components/mermaidMap/SingleSiteMap/SingleSiteMap.js
src/language.js

[updates made on trello card](https://trello.com/c/ZBgnL5DE/)

[633[ Pin button should disappear after placing pin or updating lng/lat

---

src/App/routes.js
src/components/NavMenu/NavMenu.js
src/components/icons.js
src/components/pages/Gfcr/Gfcr.js
src/components/pages/Gfcr/Gfcr.stories.js
src/components/pages/Gfcr/Gfcr.styles.js
src/components/pages/Gfcr/Gfcr.test.js
src/components/pages/Gfcr/index.js
src/components/pages/GfcrIndicatorSet/GfcrIndicatorSet.js
src/components/pages/GfcrIndicatorSet/GfcrIndicatorSet.test.js
src/components/pages/GfcrIndicatorSet/index.js
src/components/pages/GfcrIndicatorSet/indicatorSetFormInitialValues.js
src/language.js

Create Gfcr and GfcrIndicatorSet components based on Site/Sites components.
Note that the Gfcr component is far from complete.
Ref: #742

Feature: Indicator set table

---

src/components/generic/form.js
src/components/pages/Site/Site.js
src/components/pages/gfcrPages/GfcrIndicatorSet/GfcrIndicatorSet.js
src/components/pages/gfcrPages/GfcrIndicatorSet/indicatorSetFormInitialValues.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/GfcrIndicatorSetForm.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subForms/F1Form.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subForms/F2Form.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subForms/IndicatorSetForm.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subForms/index.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subForms/subForms.styles.js
src/language.js
src/library/enforceNumberInput.js

Add F1 and F2 "sub forms".
Refactoring to DRY up code.
Add class names to InputRow and LabelContainer styled components to allow styling as sub classes of GFCR components. Add language for F1 and F2.
Create reusable function from enforceNumberInput.

Feat: F1 and F2

---

src/components/NavMenu/NavMenu.js
src/components/pages/gfcrPages/Gfcr/Gfcr.js
src/components/pages/gfcrPages/GfcrIndicatorSet/GfcrIndicatorSet.js
src/components/pages/gfcrPages/GfcrIndicatorSet/indicatorSetFormInitialValues.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/GfcrIndicatorSetForm.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subForms/F1Form.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subForms/F2Form.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subForms/F3Form.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subForms/IndicatorSetForm.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subForms/index.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subForms/subForms.styles.js
src/language.js

Add F3 subform.
Add language for F3.
Add StyledGfcrSubInputWrapper styled component.
Ref: https://trello.com/c/oS8xVh7m/772-f3

Feat: F3 questions

---

src/components/pages/gfcrPages/GfcrIndicatorSet/GfcrIndicatorSet.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/GfcrIndicatorSetForm.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/modals/FinanceSolutionModal.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/modals/InvestmentModal.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/modals/RevenueModal.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/modals/financeSolutionInitialValues.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subPages/FinanceSolutions.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subPages/Investments.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subPages/Revenues.js
src/language.js

Display revenue type in revenue table.
Increase width of empty tables.
Display "None" for "Used an incubator" in finance solutions table.
Display "finance solutions" link in empty revenue and investments tables.
Refactor submit and delete functions.

Fix: Investments, revenues

---

src/components/icons.js
src/components/pages/ImageClassification/ImageClassificationTable.js
src/components/pages/ImageClassification/SampleUnitInputSelector.js
src/components/pages/collectRecordFormPages/BenthicPhotoQuadratForm/BenthicPhotoQuadratForm.js
src/language.js

[trello card](https://trello.com/c/7bAtoXXm/795-sample-unit-input-selector)
the beginning template for the sample unit selector - not sure what we are adding in the description yet, so lorum ipsum text is there

[795] image classification: sample unit selector

---

src/components/mermaidInputs/InputNoRowSelectWithLabelAndValidation/InputNoRowSelectWithLabelAndValidation.js
src/components/mermaidInputs/InputNoRowWithLabelAndValidation/InputNoRowWithLabelAndValidation.js
src/components/pages/gfcrPages/Gfcr/NewIndicatorSetModal.js
src/components/pages/gfcrPages/GfcrIndicatorSet/GfcrIndicatorSet.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subPages/F1Form.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subPages/F2Form.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subPages/F3Form.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subPages/F4Form.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subPages/F5Form.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subPages/F6Form.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subPages/F7Form.js
src/components/pages/gfcrPages/GfcrIndicatorSetForm/subPages/ReportTitleAndDateForm.js
src/language.js

Add language, functions and links to langauge file.
Update helper text behaviour. Info icons behave independently of show/hide help button.
Update FxForm files to use new helper text functions.
Add date validation to report title and date forms.
Start using language file in ReportTitleANdDateForm.
Ref: https://trello.com/c/psr9nM6H/794-gfcr-helper-text

Feat: Helper Text

---

src/App/mermaidData/databaseSwitchboard/ImageClassificationMixin.js
src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.js
src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.styles.js
src/components/pages/ImageClassification/ImageUploadModal/ImageUploadModal.js

- add uploadImage api processing request
- one post per image in a multi-form
- add status row to table
- add placeholder for polling logic
next: 
- add polling logic
- add get all images in project to image classification mixin
to test:
- ensure we are getting back `imageData` in `processSingleImage`

[1001] upload image api

---

src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.js

[trello ticket](https://trello.com/c/PMiwmk0D/1014-image-classification-fetch-images-when-loading-collect-record)
fetch image classification images when a collect record loads
to test:
1. upload images
2. refresh

[1014] fetch images on load

---

src/components/pages/ImageClassification/SampleUnitInputSelector/SampleUnitInputSelector.js
src/components/pages/ImageClassification/SampleUnitInputSelector/SampleUnitInputSelector.styles.js
src/components/pages/ImageClassification/SampleUnitInputSelector/SampleUnitInputSelectorOffline.js
src/components/pages/collectRecordFormPages/BenthicPhotoQuadratForm/BenthicPhotoQuadratForm.js
src/language.js

[trello card](https://trello.com/c/ndfhZ4gp/897-disable-image-classification-offline)
to test:
1. create a BPQ record
2. go offline
3. see sample unit selector switch to offline text
4. go back online
5. select image classification
6. go offline again
7. see table switch to offline text

[M897] disable ic offline

---

src/components/pages/gfcrPages/Gfcr/Gfcr.js

[trello card](https://trello.com/c/zKPCzFVV/1151-gfcr-page-title-is-sites)

[M1151] fix site title for GFCR

---

src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.js

[trello card](https://trello.com/c/2eZd5Dcc/1140-update-table-header-from-thumbnail-to-photo)

M1140: update table header text ic

---

src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.js
src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.styles.js

[trello card](https://trello.com/c/U3U5rc0K/1071-ic-adjust-table-highlighting-css)
photo, review and delete buttons remain highlighted for each image group

[M1071] table highlighting css

---

src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.js
src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.styles.js

[trello card](https://trello.com/c/U3U5rc0K/1071-ic-adjust-table-highlighting-css)

[M1071] remove unnecessary table CSS grouping

---

src/components/pages/ProjectInfo/ProjectInfo.js

[trello card](https://trello.com/c/J2ejeUy6/1085-clean-up-gfcr-user-testing-constraint)
- small update to remove outdated code related to `isGfcrUserTester`

M1085 remove outdated isGfcrUserTester code

---

src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/SelectAttributeFromClassifierGuesses.js

Description: ensure that previous selected point's info doesnt bleed into newly selected point popup.
[Ticket](https://trello.com/c/IhyWQJNq/1227-update-default-state-of-attribute-selector-to-choose)
Steps to test:
- go to BPQ review
- click a point
- select an attribute from dropdown
- click another unconfirmed point
- notice that the dropdown for the new point should not have the previously selected value
- click another point
- select 'select new attribute' from the dropdown
- enter another attribute and click 'add row'
- click on another unconfirmed point
-  notice that the dropdown for the new point should not have the newly added attribute value

Image classification/m1227 classifier select doesnt clear properly

---

src/components/FilterSearchToolbar/FilterSearchToolbar.js
src/components/NewAttributeModal/NewAttributeModal.js
src/components/pages/collectRecordFormPages/BenthicPhotoQuadratForm/BenthicPhotoQuadratTransectInputs.js

removing easy-to-remove console errors

Remove easy-to-remove console warnings

---

src/components/NavMenu/NavMenu.js
src/language.js

M1328 more corrections

---

src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.js

Ticket: https://trello.com/c/npLkY3Dr/1379-review-column-should-span-to-the-unclassified-row-as-well-1

Image classification/m1379 bpq row hover 2
