data-mermaid/mermaid-webapp

src/App/integrationTests/managementRegime/App.managementRegimeCreateOffline.test.js
src/App/integrationTests/site/App.siteEdit.test.js
src/App/integrationTests/sites/App.siteCreateOffline.test.js
src/components/pages/ManagementRegime/ManagementRegime.js
src/components/pages/Site/Site.js
src/language.js

Steps to test:
- create a new site while offline. 
- click save
Expected results
- a toast with "The site has been saved on your computer." shows
Do the same when online: Expect the toast to say "The site has been saved on your computer and in the MERMAID online system."
Repeat (online and off) for saving an MR

fix: M971 misleading site save messaging when offline

---

src/App/mermaidData/databaseSwitchboard/ProjectHealthMixin.js
src/testUtilities/mockMermaidApiAllSuccessful.js

Id save testing for @alanjleonard 
(I couldnt reproduce this on the newly downloaded FF dev edition. Perhaps they fixed the bug? I added the trailing slach as @saanobhaai mentioned in the ticket regardless)
See ticket for more info if you want: https://trello.com/c/gbfLStlT/963-send-token-with-redirected-requests

fix: 963 added trailing slash to project summary endpoint to avoid 301 responses

---

src/components/pages/ProjectInfo/ProjectInfo.js
src/language.js

to test: 
- sign in as a read only user for a project (you may need to create read-only or collector new user for yourself at an email alias eg `julia+test1@sparkgeo.com`)
- navigate to project info page
- expect that there is a project name included in the project info

fix: 975 include project name on project info page

---

src/components/pages/DataSharing/DataSharing.js
src/language.js
src/library/constants/constants.js

To test:
- Login to a project that you are admin on
- Go to the data sharing page, toggle the 'this is a test project' checkmark to be checked
- log out, 
- log back in as a user that is read only or collector
- view the data sharing page
Expected results: 
- you should see some text that says 'This is a test project' with no checkbox input (because we are read only now)
Other test:
- log back in as admin
- go to datasharing page
- toggle the 'This is a test project' checkbox to be unchecked
- log out and back in as a read only or collector
- view the data sharing page
Expected results: 
- you should NOT see text that says 'This is a test project' (and there should also be no checkbox for it)

fix: 975 data sharing page. Added missing info for read only mode.

---

src/components/generic/Table/table.js
src/components/generic/form.js
src/components/pages/DataSharing/DataSharing.js
src/components/pages/Users/Users.js

[trello ticket 813](https://trello.com/c/Vqcuzicp/813-disable-controls-after-clicking-until-theres-a-response-on-data-sharing-page)
**task:** disable radio buttons on data sharing page when updating, also add wait cursor to radio button items
also disabled for checkbox on data sharing
**to test:**
1. go to data sharing & users pages
2. click a radio button to update
3. check to see that radio buttons are disabled while updating, and that wait cursor appears over radio button labels

[813] Data sharing & Users: disable controls after click

---

src/App/App.js
src/App/integrationTests/App.syncUserDeniedPushErrors.test.js
src/App/mermaidData/databaseSwitchboard/tests/testHelpers.DatabseSwitchboard.js
src/App/mermaidData/syncApiDataIntoOfflineStorage/SyncApiDataInfoOfflineStorage.test.js
src/App/mermaidData/syncApiDataIntoOfflineStorage/SyncApiDataIntoOfflineStorage.js
src/App/mermaidData/syncApiDataIntoOfflineStorage/useInitializeSyncApiDataIntoOfflineStorage.js
src/components/pages/Projects/Projects.test.js
src/language.js
src/testUtilities/mockOnlineDatabaseSwitchboardInstance.js
src/testUtilities/mockPushStatusCodes.js

a user being not allowed to push to a project now is determined by a sync status_code of 403 AND there being project info included with that sync 403 response
To test (or leave for @saanobhaai ): take the mock data included in a comment I will add and use it as a fake api response (I used Mokku to do this with dev tools)

Melissa/970 sync push denied handling 

---

Readme.md
src/App/integrationTests/app.lastRevisionNumbersForSyncing.test.js
src/App/mermaidData/getIsDataTypeProjectAssociated.js
src/App/mermaidData/lastRevisionNumbers.js
src/App/mermaidData/lastRevisionNumbers.test.js
src/App/mermaidData/pullApiData.js
src/testUtilities/initiallyHydrateOfflineStorageWithMockData.js
src/testUtilities/mockMermaidApiAllSuccessful.js

Steps to test:
User A: add User B to project
User B: go to any project page
User A: remove User B from project
User B: go to Projects (list) page (project no longer there)
User A: add User B back to project
User B: refresh Projects (list) page (project there again)
User B: go to Sites, MRs, or Users pages
Expected behavior:
User B sees same Sites, MRs, and Users as User A
Original ticket: https://trello.com/c/54Q80ITc/981-users-local-data-not-refreshed-after-being-removed-then-added-to-project

fix: 981 make sure sites, MRs, users page get refreshed after user readded to project

---

src/components/pages/collectRecordFormPages/BenthicLitForm/BenthicLitForm.js
src/components/pages/collectRecordFormPages/BenthicPhotoQuadratForm/BenthicPhotoQuadratForm.js
src/components/pages/collectRecordFormPages/BenthicPitForm/BenthicPitForm.js
src/components/pages/collectRecordFormPages/BleachingForm/BleachingForm.js
src/components/pages/collectRecordFormPages/CollectRecordFormPage/CollectRecordFormPage.js
src/components/pages/collectRecordFormPages/CollectRecordFormPageAlternative/CollectRecordFormPageAlternative.js
src/components/pages/collectRecordFormPages/FishBeltForm/FishBeltForm.js
src/components/pages/collectRecordFormPages/HabitatComplexityForm/HabitatComplexityForm.js
src/library/getDataForSubNavNode.js

[trello ticket](https://trello.com/c/MaBgWnf4/946-collect-record-title-sub-nav-node-title-dont-refresh-when-inputs-updated-and-saved)
previously, titles would only update in a manual refresh after saving
now, titles update automatically on save
to test:
1. add a collect record
2. add site name, transect number
3. save
4. check to see that both titles update (nav and sub nav)
5. update site name & transect number again with new items
6. check to see that items update again
7. repeat for each protocol

946: Collect titles refresh bug

---

src/App/integrationTests/collectRecords/benthicPit/App.ObservationIntervalBenthicPit.test.js
src/App/integrationTests/collectRecords/benthicPit/App.updateBenthicPit.test.js
src/components/pages/collectRecordFormPages/BenthicPitForm/benthicPitObservationReducer.js

Steps to test:
- Create a new benthic PIT sample unit.
- Set the Interval Size to 0.1
- Add some observations (can be blank, just tab through the fields)
Expected:
Interval column starts at Interval Start and increases by Interval Size value. In this case 0.1
0.1
0.2
0.3
0.4
0.5
JS wont support giant numbers, but I tested this with the earth's circumference in meters (40070000) with an added decimal  and numbers of similar magnitude (a few orders higher) and it works.
I initially coded the interval size input to not allow more than one decimal place but it opened a can of worms and also made for some strange ux when typing. So the user can type a ton of decimal places, but the observation interval will only show one decimal place (confirmed with Kim that that only one decimal place is …

fix: 985 display only one decimal place for interval in the observation table to avoid weird floating point math

---

src/App/App.js
src/App/mermaidData/databaseSwitchboard/ProjectsMixin.js
src/App/mermaidData/databaseSwitchboard/tests/testHelpers.DatabseSwitchboard.js
src/App/mermaidData/syncApiDataIntoOfflineStorage/SyncApiDataInfoOfflineStorage.test.js
src/App/mermaidData/syncApiDataIntoOfflineStorage/SyncApiDataIntoOfflineStorage.js
src/components/pages/Projects/Projects.test.js
src/language.js
src/testUtilities/mockOnlineDatabaseSwitchboardInstance.js

Description:
This is to handle push sync error codes of 500. Will only show on project-specific pages.
It was discovered in [this ticket,](https://trello.com/c/87bMaBfN/1032-cant-add-or-remove-a-user-front-end-and-back-end-bug) so I am using that ticket for the branch number. Edit: I am creating a[ new ticket](https://trello.com/c/xGx7JS44/1035-handle-sync-push-500-status-codes) for this to make life easier for whoever QA's this and to preserve the potential back end bug that is the in the previous ticket
Steps to reproduce:
1. add the mocked response below to a network mocking extension like Mokku for the push endpoint
1. reload the app on the projects list page
1. navigate to a project specific page
Expected results:
~~- on the project list page, there should be no toast showing~~
- on …

feat: 1032 handle push sync status codes of 500

---

src/components/ProjectCard/ProjectCardSummary.js
src/components/pages/Projects/Projects.test.js

**Describe the bug**
On the project page, the Sites sub-card should be enabled when the user is offline and a collector or admin. 
**To reproduce**
- Be a collector or an admin on a project
- Go to the projects page
- Set that project to Offline Ready
- Go offline
**Expected behaviour**
Sites sub-card is enabled and shows the number of sites in the project. Clicking on it navigates you to the Sites page for that project.

Nick/M1033 Sites sub-card on the project card improvement

---

src/components/BleachingColoniesBleachedSummaryStats/BleachingColoniesBleachedSummaryStats.js

[trello card](https://trello.com/c/UfEi0d0T/1056-the-bleaching-summary-does-not-calculate-correctly-for-normal-and-pale)
to test:
1. add a new bleaching collect page
2. go to 1st observation table
3. add a few rows and fill in numbers
4. ensure %'s add up to 100

Fix percentage calculation in bleached colonies

---

src/components/generic/InputNumberNoScroll/InputNumberNoScroll.js
src/components/generic/InputNumberNumericCharctersOnly/InputNumberNumericCharactersOnly.js
src/components/generic/InputNumberNumericCharctersOnly/index.js
src/components/pages/collectRecordFormPages/BenthicLitForm/BenthicLitObservationTable.js
src/components/pages/collectRecordFormPages/BenthicPhotoQuadratForm/BenthicPhotoQuadratObservationTable.js
src/components/pages/collectRecordFormPages/BleachingForm/ColoniesBleachedObservationsTable.js
src/components/pages/collectRecordFormPages/BleachingForm/PercentCoverObservationsTable.js
src/components/pages/collectRecordFormPages/FishBeltForm/FishBeltObservationTable.js
src/components/pages/collectRecordFormPages/FishBeltForm/tests/FishBeltObservationTable.test.js

fixes [1057](https://trello.com/c/TsgPnWPj/1057-allow-only-numbers-in-the-bleaching-su) **Allow only numbers in the Bleaching SU** & [1058](https://trello.com/c/hFsbLyp1/1058-disable-adding-minus-sign-in-the-observation-tables-for-fish-belt-benthic-lit-and-bpq) **Disable adding minus (-) sign in the observation tables for fish belt, benthic LIT, and BPQ**
main change here is that I am getting rid of `type = number` and replacing it with `<input type="text" inputmode="numeric" pattern="[0-9]*"> ` for `InputNumberNoScroll`
problems with type = number
-  includes characters such as ., -, + , and e which we don't want
- ignores `pattern="[0-9]*"`
- min/max attributes can easily be bypassed
- accessibilty: cannot be [dictated or selected when using Dragon Naturally …

Fix number inputs on observation tables

---

src/components/pages/ManagementRegime/ManagementRegime.js
src/components/pages/ManagementRulesInput/ManagementRulesInput.js
src/components/pages/collectRecordFormPages/BleachingForm/BleachingTransectInputs.js

note : wanted to make these as separate prs but accidentally made a commit to the same branch so just leaving it since they're both relatively small tasks
[trello card 1](https://trello.com/c/ocsQTJbZ/1010-add-disabled-number-field-to-bleaching-cr)
[trello card 2](https://trello.com/c/LZNZRIFR/1031-mr-rules-field-should-have-a-red-asterisk)
**Summary**
task 1: add disabled Number field to Bleaching CR - labeled Number and appearing above Label.
task 2: MR Rules field name should have a red asterisk to indicate it’s required
to test:
first task
1. go to new bleaching collect record
2. ensure number field exists and is disabled
second task
1. go to management rules
2. add new rule
3. check to see that rules has an asterisk

Add disabled number field to bleaching transect inputs + Required indicator to MR rules

---

src/App/mermaidData/databaseSwitchboard/ProjectHealthMixin.js

[trello card](https://trello.com/c/ntjxdn80/1022-change-ordering-of-su-numbers-in-mr-overview)
previous behaviour:
- transect numbers would appear as `10, 1, 2, 3, 4, 5, 6, 7, 8, 9` instead of `1, 2, 3, 4, 5, 6, 7, 8, 9, 10`
to test:
1. go to a project with at least a few records for an MR (I use Belize Glover's Atoll 2020)
2. go. to MR overview page
3. ensure numbers are ordered properly:

Add number sort to management regimes label

---

src/components/pages/DataSharing/DataSharing.js

[trello ticket ](https://trello.com/c/FKkSLucU/382-incorrect-cursor-on-data-sharing-page)
previously, the cursor was set to `pointer` on the entire page instead of `auto`
to test:
1. go to data sharing page
2. cursor should be auto instead of pointer outside of buttons

Switch cursor to auto on data sharing page

---

src/components/pages/collectRecordFormPages/FishBeltForm/ClearSizeValueModal.js
src/components/pages/collectRecordFormPages/FishBeltForm/FishBeltTransectInputs.js
src/components/pages/collectRecordFormPages/FishBeltForm/tests/FishBeltObservationTable.test.js
src/language.js

[trello card](https://trello.com/b/XeUt1nb5/mermaid-dev)
Users should be able to change the fish size bin even if there are observations. Show a modal confirmation that the "Size" value will be cleared for all observations.
To test:
1. add a new fish belt record
2. select a bin size
3. add observations
4. change bin size
5. modal should appear with a warning that sizes will be cleared if they accept
6. check to see that sizes are cleared if you click ok

Remove disabled fish belt bin sizes - add clear sizes modal

---

src/components/generic/InputAutocomplete/InputAutocomplete.js
src/components/generic/InputAutocomplete/InputAutocomplete.styles.js
src/components/pages/collectRecordFormPages/BenthicLitForm/BenthicLitObservationTable.js
src/components/pages/collectRecordFormPages/BenthicPhotoQuadratForm/BenthicPhotoQuadratObservationTable.js
src/components/pages/collectRecordFormPages/BenthicPitForm/BenthicPitObservationTable.js
src/components/pages/collectRecordFormPages/BleachingForm/ColoniesBleachedObservationsTable.js
src/components/pages/collectRecordFormPages/FishBeltForm/FishBeltObservationTable.js

[trello card](https://trello.com/c/G4VoLKkl/384-all-autocomplete-in-the-observation-table-should-detect-if-its-at-the-top-or-bottom-of-the-page-and-open-up-as-opposed-to-down-s)
Previously the autocomplete menu would get cut off when expanded. 
Added a scroll-to-bottom-of-page function when entering text into the autocomplete observation menu. Set a rule that this only happens when you are entering data in the last row of the table so it doesn't jump to the bottom of the screen at row 25/50 for example.
to test:
1. go to a collect record that has an observation table auto-complete (benthic lit/pit/BPQ/bleaching/FB)
2. scroll down to observation table
3. begin entering text to see expanded menu (try 'cli) for example
4. notice that the menu stays in viewport
5. add a bunch more rows (10 …

Add scroll-to-bottom when on last row of observation table autocomplete

---

src/components/pages/collectRecordFormPages/FishBeltForm/FishBeltObservationTable.js

[trello ticket ](https://trello.com/c/aqNCQdit/496-still-able-to-add-observations-to-a-fish-belt-if-fish-size-bin-isnt-selected)
to test:
1. add a fish belt collect record
2. try and add an observation without selecting a bin size
3. add-row should be disabled, in addition to any text inputs
4. tab and enter should also be disabled to add a new row

[496] disable observations if bin size not selected

---

src/components/pages/Users/Users.js

[trello ticket](https://trello.com/c/XwCyweuS/360-mouse-shows-clickable-anywhere-on-submitted-row-but-clicking-only-goes-to-su-in-the-method-column)
note: other tables were fixed in a separate pr - but good to cross check just incase:
collecting
submitted
Sites
MRs
Users
Observations
to test:
1. go to users page table
2. hover over radio buttons
3. pointer cursor shows over labels/inputs
4. auto cursor shows when button is disabled 
5. wait cursor shows when updating

[360] Cursor fix for table on users page

---

src/components/pages/ManagementRegimesOverview/ManagementRegimesOverview.js

Added methods filter on management regimes overview table similarly to Collect, Submitted, Users and Transects table
current bug:
1. go to MRO table
2. add a filter
3. refresh
4. get `TypeError:  Cannot read properties of undefined (reading 'props')`
my suspicion is that there may be another race condition happening here, but i'm not 100% sure. The type error is happening because` tableCellData` is missing data (only `site` and `method` appear, without `sampleUnitNumbers`, ie those long ids in the object you see below)
normal `tableCellData`
what `tableCellData` looks like when its logged in the `_applyMethodsFilterOnLoad` function
my guess is that line 187  `...populateSampleUnitNumbersByManagementRegimeRow(record)` isn't finished populating before it is used within …

implement Methods filter on MRO table [debugging]

---

src/components/pages/collectRecordFormPages/CollectRecordFormPage/CollectRecordFormPage.js
src/library/useUnsavedDirtyFormDataUtilities.js

[trello card](https://trello.com/c/ZT7EohIk/507-observations-disappear-when-goes-online-after-inputting-offline)
previously if you were on a new form and you entered data into observations and refreshed the page, it would get wiped out
also fixed second bug which wiped out persisted data when an observer was clicked and the page was refreshed or toggled from offline to online
to test:
// for refreshing
1. create a new collect record
2. add a few observations
3. refresh
4. observations should persist
// for offline to online
1. create a new collect record while offline
2. add observations + observer + transect inputs
3. toggle online
4. all items should persist

[507] Bug fix for observations persist issue 

---

src/components/ColumnHeaderToolTip/ColumnHeaderToolTip.js
src/components/generic/Table/table.js
src/components/generic/links.js
src/components/pages/Site/Site.js
src/components/pages/Users/Users.js
src/components/pages/collectRecordFormPages/BenthicLitForm/BenthicLitObservationTable.js
src/components/pages/collectRecordFormPages/BenthicLitForm/BenthicLitTransectInputs.js
src/components/pages/collectRecordFormPages/BenthicPhotoQuadratForm/BenthicPhotoQuadratObservationTable.js
src/components/pages/collectRecordFormPages/BenthicPhotoQuadratForm/BenthicPhotoQuadratTransectInputs.js
src/components/pages/collectRecordFormPages/BenthicPitForm/BenthicPitObservationTable.js
src/components/pages/collectRecordFormPages/BenthicPitForm/BenthicPitTransectInputs.js
src/components/pages/collectRecordFormPages/BleachingForm/BleachingTransectInputs.js
src/components/pages/collectRecordFormPages/BleachingForm/PercentCoverObservationsTable.js
src/components/pages/collectRecordFormPages/FishBeltForm/FishBeltObservationTable.js
src/components/pages/collectRecordFormPages/FishBeltForm/FishBeltTransectInputs.js
src/components/pages/collectRecordFormPages/HabitatComplexityForm/HabitatComplexityTransectInputs.js
src/language.js

[trello card](https://trello.com/c/qRpY0zIj/487-column-header-tool-tip)
summary:
add info icon to some column headers to provide more context to users
to test:
1. refer to [mermaid terms list](https://docs.google.com/spreadsheets/d/1CpGEMW_qF7XeI52H-gvZZKM8cwhHDg6yV7eUbnyFE6M/edit?pli=1#gid=2048735771) to check out which items have added tool tips
2. go to users page (for example)
3. click on admin/collector/read-only info icon
4. observe pop up text
5. click away from tool tip to close it

[487] Column tool tip

---

src/components/generic/Table/PageSizeSelector/PageSizeSelector.js
src/components/pages/Collect/Collect.js
src/components/pages/ManagementRegimes/ManagementRegimes.js
src/components/pages/ManagementRegimesOverview/ManagementRegimesOverview.js
src/components/pages/Sites/Sites.js
src/components/pages/Submitted/Submitted.js
src/components/pages/Users/Users.js
src/components/pages/UsersAndTransects/UsersAndTransects.js

[trello card](https://trello.com/c/Ozx70QNw/505-update-pagination-count-for-filtering)
updates pagination count at the bottom of a table when any filters are applied (search or methods filtering)
tables updated: MRO, MR, users, collecting, submitted, users & transects, sites
to test:
1. go to any of the tables listed above
2. add text into the search field
3. pagination should be updated to include filtering text, as well as the amount of rows that are currently in the table

[505] Update pagination count

---

src/components/ObservationAutocomplete/ObservationAutocomplete.js
src/components/generic/InputAutocomplete/InputAutocomplete.js

[trello card](https://trello.com/c/tVY3uzyb/371-the-tab-button-cannot-select-a-highlighted-country-option-in-the-add-new-site-module)

[371] fix tab-select for country drop down

---

src/components/pages/collectRecordFormPages/BenthicPhotoQuadratForm/BenthicPhotoQuadratForm.js

Steps to test:
- Make a new benthic photo quadrat collect record
- fill out the entire form
- click save
Expected results
- on the saved page, all the values are as they were entered prior to clicking the save button

[575] fix missing benthinc photo quadrat values

---

.github/workflows/_cdk.yml
.github/workflows/_preview-create.yml

Im assuming `_cdk.yml` default env values are what are used in production and have left the dashboard link env var there untouched (pointing to `https://dashboard.datamermaid.org`), but this should be confirmed.

M292 - have preview links use the dev version of dashboard

---

.env.sample
.github/workflows/_cdk.yml
.github/workflows/_preview-create.yml
Readme.md
public/index.html

Opt into tracking with an environment variable. `REACT_APP_CAPTURE_GOOGLE_ANALYTICS=true`. If this environment variable is not present and set explicitly to true, no tracking will occur. (our secure note for env vars has been updated)
Other options considered:
- Hostname filters within Google Analytics interface. (requires learning the nuances of that process with Google Analytics, which less of us will be able to do. Most of us can reason easily about environment vars).
- front end code to check host name and only implement analytics for `app.datamermaid.org` (which is less explicit, and tightly couples GA tracking logic to a particular host name, which feels more fragile)

M272 Control if the app captures Google Analytics data with environment variables.

---

src/components/generic/form.js
src/components/mermaidMap/SingleSiteMap/SingleSiteMap.js
src/components/pages/Site/Site.js
src/library/numbers/roundToSixDecimalPlaces.js

[Ticket](https://trello.com/c/1ly7Aigw/588-round-lat-and-long-to-6-digits-of-precision-to-right-of-decimal)

M588 store only 6 decimal places for a site's lat and lng (unless the user types more).

---

src/App/mermaidData/fishNameHelpers.js
src/components/pages/collectRecordFormPages/FishBeltForm/FishBeltObservationTable.js

Steps to test:
- go to a fish belt
- add an observation for a species, a genus and a family. (I used Chlorurus bleekeri, Pseudanthias, and Scaridae)
- click the popover for each
Expected results:          
- for a species, and a genus,  a row with the family name will show. 
- for family, no family row will show (because the table label contains the family name already)

M369 make sure fish family name shows in fish name popover for fish belt species and genera observations

---

src/App/App.js
src/App/integrationTests/managementRegime/App.managementRegimeCreateOffline.test.js
src/App/mermaidData/databaseSwitchboard/ProjectsMixin.js
src/App/mermaidData/databaseSwitchboard/SubmittedRecordsMixin.js
src/App/useInitializeCurrentUser.js
src/components/pages/ManagementRegime/ManagementRegime.test.js
src/components/pages/submittedRecordPages/SubmittedFishBelt/SubmittedFishBelt.js

The API is sensitive to the absence of a trailing slash and if it is missing will cause a redirect, which results in multiple calls to  `projecttags/` and
`projecttags`
for example.

M287 remove excessive network calls

---

src/components/pages/collectRecordFormPages/BleachingForm/ColoniesBleachedObservationsTable.js

[trello card](https://trello.com/c/2dmq0XSL/622-bleaching-observation-table-automatically-move-up-when-typing-ba)
removed `isLastRow` for Colonies Bleached table. Left the check on Percentage Cover, since it is the last table on the page (in which case, we don't mind that it scrolls to bottom).

M622 bleaching observation table jumping bug fix

---

src/components/generic/form.js
src/components/mermaidInputs/InputWithLabelAndValidation/InputWithLabelAndValidation.js
src/components/pages/collectRecordFormPages/BenthicPitForm/BenthicPitTransectInputs.js
src/components/pages/collectRecordFormPages/collectRecordFormInitialValues.js
src/language.js

[trello card](https://trello.com/c/z70S6wyM/642-help-text-for-interval-start-in-pit-is-incomplete)
to test:
1. add new collect record
2. ensure interval start has no default value
3. add interval size number input
4. check "Use Interval Size as Interval Start"
5. notice interval start sync to interval size value and change to a disabled field
6. if unchecked, you can update both inputs individually

[642] add sync interval start button to Benthic pit

---

src/components/generic/buttons.js
src/components/generic/form.js
src/components/icons.js
src/components/mermaidInputs/InputSelectWithLabelAndValidation/InputSelectWithLabelAndValidation.js
src/components/mermaidInputs/InputWithLabelAndValidation/InputWithLabelAndValidation.js
src/components/pages/Site/Site.js
src/components/pages/collectRecordFormPages/BenthicPitForm/BenthicPitTransectInputs.js
src/language.js

[trello card](https://trello.com/c/RddqoivR/632-provide-a-button-to-switch-lat-and-long-when-creating-or-updating-a-site-map)
to test:
1. add a new site
2. enter long or lat value
3. press swap button
4. should swap values and update pin on map
5. buttons should be disabled if no lng or lat values (both have to be empty)

[632] add long lat swap button to site form

---

src/App/mermaidData/databaseSwitchboard/DatabaseSwitchboard.js
src/App/mermaidData/databaseSwitchboard/GfcrMixin.js
src/components/generic/ButtonSecondaryDropdown/ButtonSecondaryDropdown.js
src/components/generic/ButtonSecondaryDropdown/ButtonSecondaryDropdown.styles.js
src/components/pages/Gfcr/Gfcr.js
src/components/pages/Gfcr/Gfcr.styles.js
src/components/pages/Submitted/SubmittedToolbarSection.js
src/language.js

**Environment setup required to test:**
Checkout the `M739` `mermaid-api` branch and run `make freshinstall && make runserver`. The latest API changes for GFCR are on this branch.
**Note:**
Used "Export" icon to remain consistent with 'submitted toolbar' elsewhere in application.
**Summary of changes:**
- Add no data message to GFCR indicator sets table.
- Add "Create new" and "Export" buttons.
- Get GFCR indicator sets from API.
- Add GfcrMixin class.
- Update styles to be more reusable/generic.
**Refs:** https://trello.com/c/UeuZSAiw/728-no-data-screen, https://trello.com/c/UWqjgxJ3/729-button-bar

Feature: No data screen

---

src/components/pages/ImageClassification/ImageClassificationContainer.js
src/components/pages/ImageClassification/ImageUploadModal.js

- add validations/error toasts for max image upload size, duplicates, and file types
to test:
1. go to collections
2. add new BPQ
3. scroll down to observations
4. click image classification
5. click upload photos
6. try testing different file types (single and batches)

Image classification: modal image drop file validations

---

src/components/pages/ImageClassification/ImageUploadModal/ImageUploadModal.js

prevents a weird bug where first batch of uploads wouldn't work, and just reopened the file drop

[909] small fix: adjust on click handler for dropzone in image drop modal

---

src/components/pages/ImageClassification/ImageUploadModal/ImageUploadModal.js
src/components/pages/ImageClassification/SampleUnitInputSelector.js
src/components/pages/ImageClassification/sampleData/image_endpoints.md
src/components/pages/collectRecordFormPages/BenthicPhotoQuadratForm/BenthicPhotoQuadratForm.js
src/components/pages/collectRecordFormPages/CollectRecordFormPage/CollectRecordFormPage.js
src/components/pages/collectRecordFormPages/reformatFormValuesIntoRecord.js

[trello card](https://trello.com/c/oLNAU1a4/990-ic-create-new-collect-record-when-selecting-image-classification)
- when a user selects either image classification or manual input for a BPQ observation table, save the record
- added `image_endpoints.md` in as sample data
to test:
1. create a new BPQ record
2. select IC or manual input
3. ensure record saves automatically

[910] create new collect record when selecting ic

---

src/App/mermaidData/databaseSwitchboard/ImageClassificationMixin.js
src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.js
src/components/pages/ImageClassification/ImageUploadModal/ImageUploadModal.js
src/components/pages/collectRecordFormPages/BenthicPhotoQuadratForm/BenthicPhotoQuadratForm.js
src/components/pages/collectRecordFormPages/CollectRecordFormPage/CollectRecordFormPage.js
src/components/pages/collectRecordFormPages/reformatFormValuesIntoRecord.js
src/library/constants/constants.js

- add `getAllImagesInProject` to mixin
- add  `pollImageStatuses` to observation table (occurs every 5 seconds until all images are done processing)
-  update property to `image_classification` (instead of camel case) for api 
next: fill in the number of points columns with confirmed/unconfirmed/etc
to test:
1. create a new BPQ record
2. upload images
3. observe status showing pending in table
4. wait for status to change to completed
5. image thumbnail click and review button get activated
note 
- waiting for an api update to pass in collect record as query. right now, all project images get added into a record when polling

[1006] add polling for images

---

src/App/mermaidData/databaseSwitchboard/ImageClassificationMixin.js
src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.js
src/components/pages/ImageClassification/ImageUploadModal/ImageUploadModal.js
src/library/constants/constants.js

few minor changes here..
bugs
- ensure polling stops after all images are processed
- ensure no duplicate images are added (adjust data path)
- rename image classification mixin to `getAllImagesInCollectRecord` instead of `getAllImagesInProject`

Image classification: fix polling bug

---

src/components/mermaidMap/mapService.js

[trello ticket](https://trello.com/c/0U9dK0sX/1013-add-new-site-error)
console error `layer with id clusters does not exist on map` no longer appears. Added check to ensure clusters are loaded before adding layers.
to test, go to single site map, add site, open up console
I did notice another error that is currently on dev on sites and now appears on single site map: `Error: Could not load image because of The source image could not be decoded.. Please make sure to use a supported image type such as PNG or JPEG. Note that SVGs are not supported.`
it seems to be happening within this code block in `loadACALayers` (if I comment it out it goes away):
```
map.addLayer(
{
id: 'atlas-planet',
type: 'raster',
source: 'atlas-planet',
'source-layer': 'planet',
paint: {
'raster-opacity': …
```

[M1013] add check for clusters before adding layers

---

src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.js
src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.styles.js

[trello card](https://trello.com/c/84z4ha0o/1040-ic-observation-table-design-updates)
- fixed bug where initial fetch was being called several times
- added functions to reformat/distill images and annotation data for easier table use
- got rid of status column and stretched the status across columns when its processing
- reformatted table so it no longer has header/subheader rows
todo:
- fix row highlight to match[ codepen](https://codepen.io/alanjleonard/pen/dyBBdLL?editors=1100) example
- adjust row numbers to increase for each row rather than each image
to test:
- upload images
- notice new status bar
- refresh after images are processed

[1040] IC table design updates

---

src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.js

now rows increment by row number instead of image index number
to test:
- upload images 
- ensure # column values increment by row number
- add images, ensure row number is consistent

[1058] update table index rows

---

src/components/pages/collectRecordFormPages/BenthicPhotoQuadratForm/BenthicPhotoQuadratForm.js

[trello card](https://trello.com/c/3PHeCUWS/1072-ic-bug-bpq-observation-table-disappears-when-moving-a-submitted-su-to-collecting)
add case where `image_classification === undefined` in displaying observation table

M1072 obs table bug

---

src/components/pages/collectRecordFormPages/BenthicPhotoQuadratForm/BenthicPhotoQuadratForm.js

[trello card](https://trello.com/c/3PHeCUWS/1072-ic-bug-bpq-observation-table-disappears-when-moving-a-submitted-su-to-collecting)
reverts previous bug fix where `enableImageClassification === undefined` was added to check which table type to display

[1072] revert fix for ic bug - needs more testing

---

src/components/pages/collectRecordFormPages/BenthicPhotoQuadratForm/BenthicPhotoQuadratForm.js
src/components/pages/collectRecordFormPages/CollectRecordFormPage/CollectRecordFormPage.js

[trello card](https://trello.com/c/gM5BG5cj/1083-ic-bug-isimageclassification-gets-reset-when-a-user-validates-bpq-record-sample-unit-selector-shows-up-again)
- added check in `handleSave` to ensure `image_classification` does not get over written
- renamed var to differentiate between IC  stored value and the UI-driven state

[M1083] bug fix for is ic getting reset

---

src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.js
src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.styles.js
src/components/pages/collectRecordFormPages/CollectingFormPage.Styles.js

[trello card](https://trello.com/c/zLTcNJIN/1088-minor-ui-updates-for-observation-table)
updates:
- Center the thumbnail vertically and horizontally
- The border on thumbnail hover shouldn’t shift the layout. Try using outline instead of border.
- The sticky table header should include both header rows. Currently just the Confirmed Unconfirmed Unknown are sticky
- Table headers should align with the content in the columns. Numbers are aligned right, text left.
- Growth Form header should be aligned left
- Confirmed, Unconfirmed, and Unknown should be aligned right, but keep Number of Points centered
**need clarification - uploads happen in the upload status bar (toast)**
updated remaining statuses (queued, processing)
Statuses need to be updated
Before being uploaded: “Queued”
While being …

M1088: UI updates

---

src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModalMap.js
src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationContainer.js
src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.js
src/components/pages/collectRecordFormPages/BenthicPhotoQuadratForm/BenthicPhotoQuadratForm.js
src/components/pages/collectRecordFormPages/CollectRecordFormPage/getObservationValidationInfo.js
src/components/pages/collectRecordFormPages/CollectingFormPage.Styles.js
src/language.js

[trello card](https://trello.com/c/lSlVf7Hf/1076-handle-pqt-validation-on-frontend)
**summary**
-  added validations column to image classification
- removed unknown/unclassified column (now represented as a subrow for an image)
-  validations belong to each specific row
-  unconfirmed data points correspond to each row
-  warning/error colors  appear for each row depending on validation status
- if unknown/unclassified points for an image exist, an additional subrow will get added for that specific image, which will display how many unclassified points there are
- hide observation validation row error if unconfirmed count = 0
**to test**
- create a BPQ record
- select image classification
- upload some images
- click validate
- see validations column appear with corresponding messages
- …

[M1076] handle validate

---

src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModal.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModalMap.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModalTable.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/ClassifierGuesses.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/ExistingRows.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/ImageAnnotationPopup.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/NewRow.js
src/components/pages/ImageClassification/SampleUnitInputSelector/SampleUnitInputSelector.js

[trello card](https://trello.com/c/d8qkSuPN/1145-add-a-save-confirmation-when-closing-the-image-annotation-modal)
to test:
1. upload images in BPQ record
2. open image annotation modal
3. make changes (confirm, add new attribute in modal map, change classifier guess etc)
4. click 'x' or cancel (don't save changes)
5. ensure js alert pops up to show that you have unsaved changes

[M1145] Add a save confirmation when closing the image annotation modal.

---

src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModal.js

[trello card](https://trello.com/c/d8qkSuPN/1145-add-a-save-confirmation-when-closing-the-image-annotation-modal)
to test:
1. go to IC
2. upload images
3. open annotation modal
4. make changes
5. close browser tab
6. view prompt

M1145: add prompt when browser tab is being closed

---

src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/NewRow.js

Changes: The image classification point popover New Attribute modal add button is now the same as the manual observation entry button
[Ticket](https://trello.com/c/sOkvxdyu/1146-make-add-row-button-consistent?filter=member:mnunes24)
Steps to test:
Look at the screenshots. They are the same buttons now as requested in the ticket!
OR:
- open the app and create a manual-entry BPQ record. Note the 'add row' button. 
- create a image-classification BPQ record. 
- upload an image
- click 'review'
- click on an point to open the point popover
- click 'select new attribute'. Note the button to confirm is the same as to add ab observation in manual mode

M1146 button to add classification attribute consistent with manual entry button

---

src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModal.styles.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModalMap.js

[Trello card](https://trello.com/c/mKivT6DK/1184-add-loading-indicator-to-the-image-in-the-annotation-modal)
Steps to test:
- go to a BPQ record with IC
- in dev tools throttle the internet connection
- click to review the IC image
- note the image-specific loading indicator

M1184 show loading indicator over IC image until its done loading

---

src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModalMap.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/EditPointPopupWrapper.js
src/components/pages/ImageClassification/ImageAnnotationModal/usePointsGeoJson.js

[Trello ticket](https://trello.com/c/ivZFAs8Z/1156-point-pop-over-is-sometimes-cut-off-by-the-modal)
Steps to test:
- load up BPQ image review
- click on points in image making sure to zoom in and click on a sample of points on the top, right, left, and bottom. 
- notice that the popup no longer overflows outside of the image

M1156 ensure image classification image popup doesnt overflow outside of image

---

src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModal.styles.js

[Trello ticket ](https://trello.com/c/OOA1abp2/1222-zoom-icon-hover-state)(see comment with clarified requirements)
Steps to test:
- open image classification review
- hover over a row note that either the zoom cell has a hovor colour or the rest of the row. Not both at the same time. 
- select a row and note similar hover colours between the zoom cell and the rest of the row

M1122 redo hover state for IC with clarified requirements

---

src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModal.styles.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModalMap.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModalTable.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/ClassifierGuesses.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/EditPointPopupWrapper.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/ImageAnnotationPopup.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/SelectAttributeFromClassifierGuesses.js
src/components/pages/ImageClassification/useSelectNewAttribute.js

[Ticket](https://trello.com/c/WzRjXZht/1220-image-classification-point-popover-confirm-button)
Description of change:
- remove classification being autoconfirmed when user selects new classifications via any method (guesses radios, dropdown, or making a new attribute)
- ensure clicking on an unclasified point doesnt crash app (by adding optional chaining mostly)
- implement confirm button
- disable confirm button if point classification is confirmed (unless the user changes the confirmed classification to something else)
- when clicking confirm, the popover closes and the points classification is confirmed
Steps to test:
- To ensure 'unclassified' points are returned, set your API to have `CLASSIFIED_THRESHOLD = 0.5` in `src/app/settings.py` and run `make install` then start your API and …

M1220 remove auto IC confirmation when selecting attributes. Implement explicit confirm button.

---

src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/ImageAnnotationPopup.js

[Ticket](https://trello.com/c/8Pc0p1ib/1237-omit-popover-guesses-table-if-unclassified-point-is-clicked)
Hide IC guess table if point is unclassified
Steps to test:
- open BPQ record IC review
- click on unclassified point => guess table should be absent
- click on classified (confirmed or unconfirmed) point => guess table should be visible.

Image classification/m12237 omit popover table for unclassified

---

src/components/generic/Table/table.js
src/components/icons.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModal.styles.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModalMap.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/ImageAnnotationPopup.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/SelectAttributeFromClassifierGuesses.js
src/components/pages/ImageClassification/useSelectNewAttribute.js

[Ticket](https://trello.com/c/qm74tcRG/1225-image-classification-add-zoom-in-and-out-buttons-to-point-popover)
Description:
- added zoom in and out buttons
- removed semantic error in that table elements must be within a table (I had moved the select out of of the table since only the guesses can pass as appropriate to be placed in a table
Steps to test:
- open a BPQ record with image classification
- click the IC review button
- click a point in the image
- click the zoom out button => it should zoom out to the initial extent (same as reset button)
- click the zoom in button => it should zoom to the point similar to when a user clicks the point

M12235 IC reset zoom button and zoom-to-point button

---

src/components/TransferSampleUnitsModal/TransferSampleUnitsModal.js
src/components/generic/tooltip.js
src/components/icons.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModalMap.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/ImageAnnotationPopup.js
src/components/pages/ImageClassification/ImageAnnotationModal/usePointsGeoJson.js

[Ticket](https://trello.com/c/ocCH6g2a/1226-image-classification-add-next-confirmed-point-button)
Steps to test:
- open a BPQ record with image classification
- click the IC review button
- click on a point in the image
- hover over the arrow button beside the confirm button => you should see a tooltip
- click the button, it should zoom you to the next unconfirmed (classified or unclassified) point (the zoom is weird due to constraints with us hacking an image onto a map)
- confirm all the points on the map => the next unconfirmed point button should now be disabled

M1226 IC next unconfirmed button

---

src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationContainer.js
src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.js
src/components/pages/ImageClassification/ImageUploadModal/ImageUploadModal.js
src/components/pages/ImageClassification/getIsImageProcessed.js
src/components/pages/ImageClassification/imageClassificationConstants.js

Steps to test:
- go to a BPQ record with IC
- upload multiple images with network speed throttled (4g sufficient)
- look in the network tab => polling for all images for the collect record should happen no more frequently than 5 second intervals

M1244 fix polling after ic upload so that it doesnt hammer api with excessive calls

---

src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.js

[Ticket](https://trello.com/c/xlNMm5Ki/1194-missing-loading-word-and-image-name-when-uploading-images)
Prevent images with broken srcs from showing when there isnt a src value available Instead we show text based content.
Steps to test
Its hard to reproduce this reliably at the moment on my machine at least, but this is how you might see it:
- Create a new BPQ (you will need to run `make worker` from a second terminal tab while also running the mermaid api)
- Select image classification
- Upload a few (5) images => if you are lucky you _might_ see the new placeholder text instead of an image. The attached screenshot shows it as well.

M1194 show IC upload loading info and file name if no image thumbnail available

---

src/components/pages/ProjectInfo/ProjectInfo.js

Ticket: https://trello.com/c/JSGNCtud/1297-save-button-label-not-changing

M1297 ensure project info button disabled state is disabled after successful save of citation edits

---

Readme.md
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModal.styles.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/ClassifierGuesses.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/ImageAnnotationPopup.js
src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.js

[Ticket](https://trello.com/c/tXjjuaqS/1353-entire-row-of-classifier-guess-should-be-clickable-not-just-radio-button)
Changes:
- removed use of table from containing and laying our form inputs
- used label tag to have whole row clickable for classifier guesses
Steps to test:
- open the review modal for a benthic photo quadrat record ([here is a record](https://preview.app2.datamermaid.org/1183/projects/bacd3529-e0f4-40f4-a089-992c5bd5cc02/collecting/benthicpqt/a395e9ad-1ca5-4582-b84d-cc8d53fc6f1f) with an already uploaded BPQ image)
- click on an unconfirmed point to open the point popup
- select an attribute growth form
- click the label of one of the classifier guesses (not the radio itself) => this should select the associated radio

Image classification/m1353 click row select radio

---

Readme.md
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModalMap.js
src/components/pages/ImageClassification/ImageClassificationTable/ImageClassificationObservationTable.js

Tickets:
- https://trello.com/c/8YqIJT8v/1345-review-column-should-span-to-the-unclassified-row-as-well
- https://trello.com/c/fgV3EzJE/1352-disable-tilt-on-image
- https://trello.com/c/2Xrlzgyx/1348-the-zoom-when-clicking-next-attribute-is-jarring
Description of work:
- tweak a colspan so background colour on hover works as expected
- disable tilt and rotate image classification image when using touch device
- smooth out some zooming for image (that hacks a map to to achieve zoom and pan functions).
Steps to test: 
- watch the video in the first ticket and make sure that doesnt happen 
- view the app on a touch device, review a uploaded classified image, use two fingers to see if you can rotate or tilt the image. This shouldnt be possible
- click a unconfirmed point (blue square). click …

image classification - three small tickets in one PR

---

src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModalMap.js

[Ticket](https://trello.com/c/fgV3EzJE/1352-disable-tilt-on-image)
This is a redo of the oabove ticket to ensure that we can still pinch zoom on touch devices. Unfortunately Mapbox has coupled the toggle to enable zoom to the togle that enables rotate so we have to enable rotate too 👎

Reenable pinch zoom for image classification

---

package.json
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModal.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationModalMap.js
src/components/pages/ImageClassification/ImageAnnotationModal/ImageAnnotationPopup/ImageAnnotationPopup.js
src/components/pages/ImageClassification/ImageAnnotationModal/useZoomToPointsByAttributeId.js
src/components/pages/ImageClassification/imageClassificationConstants.js
yarn.lock

[Ticket](https://trello.com/c/X2Y93X1g/1385-look-into-adding-more-buffer-to-zoom-when-ic-popover-opened)
Description of work: refactored some of the base code for image classification so that we dont need weird zoom hacks to create a sub par at best zooming experience (we previously needed to zoom out before other zooming). This included updating the zoom behaviour for:
- table zoom button
- reset zoom
- next unconfirmed point button
- popup zoom in and out buttons
- clicking a point/patch when its slightly offscreen will now attempt to ensure popup is visible (this isnt perfect but it should be an improvement. Its also tuned for small laptop screensizes and fairly useless on phone screen sizes)
Steps to test:
- play with the above zoom features ensuring they work to an acceptable level. …

IC zooming refactor
